version: '3'

services:

  portainer:
    image: hypriot/rpi-portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  gateway:
    container_name: gateway
    image: radyak/gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/home/pirate/conf:/usr/src/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CONF_DIR=/usr/src/conf
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth

  test-app:
    container_name: test-app
    image: radyak/test-app
    environment:
      - PORT=3210
  
  mongodb:
    container_name: mongodb
    image: radyak/mongodb
  #   image: nonoroazoro/rpi-mongo # incompatible with currently used 'wire' driver version
  #   image: zsimo/rpi-mongo
    ports:
      - 27017:27017

