version: '3'

services:

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      args:
        - BASE_IMAGE=node:8
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/home/fvo/tmp/test-mounts:/usr/src/conf"
    environment:
      - CONF_DIR=/usr/src/conf
      - ENV=dev

  test-app:
    container_name: test-app
    build:
      context: ./test-app
      args:
        - BASE_IMAGE=node:8
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  
  auth:
    container_name: auth
    build:
      context: ./auth
      args:
        - BASE_IMAGE=node:8
    # ports:
    #   - 3000:3000
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth
    
  mongodb:
    container_name: mongodb
    build:
      context: ./mongodb
      args:
        - BASE_IMAGE=mongo
    # ports:
    #   - 27017:27017