version: '3'

services:

  gateway:
    depends_on:
      - mongodb
    container_name: gateway
    build:
      context: ./gateway
      args:
        - BASE_IMAGE=node:8
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/home/fvo/tmp/test-mounts:/usr/src/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CONF_DIR=/usr/src/conf
      - ENV=dev
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth
      - ACTIVE_CONTEXT_PROFILES=dev,local

  test-app:
    container_name: test-app
    build:
      context: ./test-app
      args:
        - BASE_IMAGE=node:8
    environment:
      - PORT=3210
    
  mongodb:
    container_name: mongodb
    image: mongo
    # build:
    #   context: ./mongodb
    #   args:
    #     - BASE_IMAGE=mongo
    ports:
      - 27017:27017


## For testing the dynamic proxy:

  # mongoclient:
  #   container_name: mongoclient
  #   image: mongoclient/mongoclient
  #   ports:
  #     - 3000:3000
  #   network_mode: host

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
